on: 
    push:
        branches: [master]
    

jobs:
    build:
        runs-on: 
          - self-hosted
          - ubutt
        steps:
          
            
            - name: Log in to Docker Hub
              run: |
                echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
                docker image build -t reehanruhullah/dataphion_prac:tagname .
                docker push reehanruhullah/dataphion_prac:tagname
                
            - name: Log in to Docker Hub
              run: |
                ansible-playbook ansible.yml -i inventory.txt

