on: 
    push:
        branches: [master]
    

jobs:
    build:
        runs-on: ubu
        
        steps:
            - run: node --version
            - run: npm --version
            - uses: actions/checkout@v4
            
            - run: node index.js
            - name: Log in to Docker Hub
              run: |
                echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
                docker image build -t reehanruhullah/dataphion_prac:tagname .
                docker push reehanruhullah/dataphion_prac:tagname

